import assert from 'node:assert/strict'
import { defaults, normalizePreferences, parsePreferences, restoreAppearance, safeBackground } from './appearance.ts'
const legacy = normalizePreferences({ palette:'forest', graph:'bar', layout:'compact', map:true })
assert.equal(legacy.schemaVersion,2)
assert.equal(legacy.cardLayout,'classic')
assert.equal(legacy.layout,'compact')
assert.equal(legacy.graph,'bar')
assert.equal(legacy.map,true)
const site=normalizePreferences({palette:'rose',modules:{clock:true,online:false}})
const override=normalizePreferences({graph:'columns',modules:{speed:false}},site)
assert.equal(override.palette,'rose'); assert.equal(override.modules.clock,true); assert.equal(override.modules.online,false); assert.equal(override.modules.speed,false)
assert.equal(defaults.modules.online,true)
for(const bad of [null,[],false,12,'text']) assert.equal(normalizePreferences(bad).palette,'default')
assert.equal(normalizePreferences({backgroundBlur:99,cardOpacity:0,cardBlur:-1,backgroundMask:Infinity}).backgroundBlur,30)
assert.equal(normalizePreferences({cardOpacity:0}).cardOpacity,55)
assert.equal(normalizePreferences({cardBlur:-1}).cardBlur,0)
for(const url of ['javascript:alert(1)','data:image/svg+xml,<svg/>','//remote.test/a','/\\remote.test/a','https://user:pass@host/a']) assert.equal(safeBackground(url),'')
assert.equal(safeBackground('/background.svg'),'/background.svg')
assert.equal(safeBackground('https://example.com/bg.png'),'https://example.com/bg.png')
assert.throws(()=>parsePreferences('{'))
assert.throws(()=>parsePreferences('null'))
assert.throws(()=>parsePreferences('{"schemaVersion":99,"palette":"rose"}'))
assert.throws(()=>parsePreferences('{"backgroundUrl":"javascript:alert(1)"}'))
assert.throws(()=>parsePreferences(' '.repeat(65537)))
const clean=parsePreferences('{"palette":"ocean","html":"<script>bad</script>","__proto__":{"polluted":true}}')
assert.equal(clean.palette,'ocean'); assert.equal(Object.hasOwn(clean,'html'),false); assert.equal(Object.hasOwn(clean,'polluted'),false)
assert.deepEqual(parsePreferences(JSON.stringify(override)),override)
const reset=restoreAppearance(legacy,site)
assert.equal(reset.palette,'rose');assert.equal(reset.map,true);assert.deepEqual(reset.modules,legacy.modules)
console.log('appearance migration, defaults precedence, validation, import/export and reset passed')

assert.equal(normalizePreferences({probe:'2'}).probe,'2')
for(const probe of ['-1','0','1.5','9007199254740993',null,{},2]) assert.equal(normalizePreferences({probe}).probe,'auto')
assert.equal(restoreAppearance(normalizePreferences({probe:'2'}),defaults).probe,'2')

assert.equal(normalizePreferences({}).homeRoutes,1)
assert.equal(normalizePreferences({homeRoutes:99}).homeRoutes,3)
assert.equal(normalizePreferences({homeRoutes:0}).homeRoutes,1)
assert.equal(normalizePreferences({homeRoutes:NaN}).homeRoutes,1)
assert.equal(restoreAppearance(normalizePreferences({homeRoutes:3}),defaults).homeRoutes,3)

// Display defaults remain compatible with old configurations and nested site values.
assert.deepEqual(normalizePreferences({}).cardInfo,{traffic:true,connections:true,uptime:true,expiry:true,remarks:true,price:true})
assert.equal(normalizePreferences({}).mobileCardInfo,null)
assert.equal(normalizePreferences({}).mobileInfoMode,'follow')
assert.equal(normalizePreferences({}).desktopColumns,'auto')
const displaySite=normalizePreferences({cardInfo:{price:false,uptime:false},desktopColumns:'3'})
assert.deepEqual(normalizePreferences({cardInfo:{price:true}},displaySite).cardInfo,{traffic:true,connections:true,uptime:false,expiry:true,remarks:true,price:true})
for(const invalid of ['8',4,-1,null,{},''])assert.equal(normalizePreferences({desktopColumns:invalid},displaySite).desktopColumns,'3')
assert.equal(normalizePreferences({cardInfo:{price:'yes'}},displaySite).cardInfo.price,false)
assert.equal(normalizePreferences({mobileCardInfo:[]}).mobileCardInfo,null)
const display=normalizePreferences({cardInfo:{price:false},mobileInfoMode:'custom',mobileCardInfo:{connections:false,uptime:false},desktopColumns:'4'})
assert.deepEqual(parsePreferences(JSON.stringify(display)),display)
assert.deepEqual(restoreAppearance(display,defaults).cardInfo,display.cardInfo)
assert.deepEqual(restoreAppearance(display,defaults).mobileCardInfo,display.mobileCardInfo)
assert.equal(restoreAppearance(display,defaults).mobileInfoMode,'custom')
assert.equal(restoreAppearance(display,defaults).desktopColumns,'4')
