import {test,expect} from '@playwright/test'
test.beforeEach(async({page})=>{await page.addInitScript(()=>{if(!localStorage.getItem('monitor-next'))localStorage.setItem('monitor-next',JSON.stringify({schemaVersion:3,infoDensity:'full',modules:{map:true}}))})})

test('compact map expands, persists and resets with all preferences',async({page})=>{
 await page.setViewportSize({width:1280,height:900})
 await page.goto('/')
 const map=page.locator('.map-frame'),height=()=>map.locator('.explorer-map').evaluate(element=>element.getBoundingClientRect().height)
 await expect(map.getByRole('button',{name:'展开地图'})).toBeVisible()
 expect(await height()).toBe(216)
 await map.getByRole('button',{name:'展开地图'}).click()
 expect(await height()).toBe(310)
 await page.reload()
 await expect(map.getByRole('button',{name:'收起地图'})).toBeVisible()
 expect(await height()).toBe(310)
 await page.getByRole('button',{name:'显示与偏好'}).click()
 await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'偏好'}).click()
 await page.getByRole('button',{name:'重置全部偏好'}).click()
 await page.getByRole('button',{name:'确认重置'}).click()
 await expect(map.getByRole('button',{name:'展开地图'})).toBeVisible()
 expect(await height()).toBe(216)
})

test('map supports zoom, pan, fit, filtering and fullscreen without stealing page scroll',async({page})=>{
 await page.goto('/')
 const map=page.locator('.explorer-map'),svg=map.locator('.explorer-stage>svg')
 await expect(map.locator('.map-land')).toBeVisible();expect(await map.locator('[data-region][role=button]').count()).toBeGreaterThanOrEqual(6)
 await expect(map.locator('.map-scale')).toHaveText('169%')
 await map.getByRole('button',{name:'放大地图',exact:true}).click()
 await expect(map.locator('.map-scale')).toHaveText('220%')
 await svg.hover();await page.mouse.wheel(0,100)
 await expect(map.locator('.map-scale')).toHaveText('220%')
 await page.keyboard.down('Control');await page.mouse.wheel(0,-200);await page.keyboard.up('Control')
 await expect(map.locator('.map-scale')).not.toHaveText('220%')
 await map.getByRole('button',{name:'适配全部',exact:true}).click()
 await expect(map.locator('.map-scale')).toHaveText('100%')
 const box=(await svg.boundingBox())!
 await page.mouse.move(box.x+60,box.y+80);await page.mouse.down();await page.mouse.move(box.x+180,box.y+100,{steps:8});await page.mouse.up()
 await expect(map.locator('.map-land')).not.toHaveAttribute('transform','translate(0 0) scale(1)')
 await expect(page.locator('.node-card')).toHaveCount(6)
 await map.getByRole('button',{name:'适配全部',exact:true}).click()
 const jp=map.locator('.populated-region[data-region="JP"]');await jp.focus();await jp.press('Enter')
 await expect(page.locator('.node-card')).toHaveCount(1)
 for(let i=0;i<3;i++)await map.getByRole('button',{name:'放大地图',exact:true}).click()
 await expect(map.locator('.map-node-preview')).toContainText('Tokyo')
 await map.getByRole('button',{name:'全屏地图',exact:true}).click()
 await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBeTruthy()
 await map.getByRole('button',{name:'退出全屏',exact:true}).click()
 await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBeFalsy()
 await map.getByRole('button',{name:'所有地区',exact:true}).click()
 await map.getByRole('button',{name:'适配全部',exact:true}).click()
 await map.screenshot({path:'tests/artifacts/map-desktop.png'})
 for(const width of [390,320]){
  await page.setViewportSize({width,height:900})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
  await expect(map).toHaveCount(0)
  await expect(page.getByRole('group',{name:'地区快速筛选'})).toBeVisible()
  await expect(page.getByLabel('表格视图')).toBeVisible()
 }
 await page.screenshot({path:'tests/artifacts/mobile-home.png'})
 await page.setViewportSize({width:1440,height:1000})
 await expect(map).toBeVisible()
})
