import {setting} from './settings'
import {test,expect} from '@playwright/test'
import {toggleSettings} from './settings'
test.beforeEach(async({page})=>{await page.addInitScript(()=>{if(!localStorage.getItem('monitor-next'))localStorage.setItem('monitor-next',JSON.stringify({schemaVersion:3,infoDensity:'full',modules:{map:true}}))})})

test('country flags appear only without map and retain the selected region',async({page})=>{
 await page.goto('/')
 await expect(page.locator('.region-atlas')).toBeVisible()
 await expect(page.getByRole('group',{name:'地区快速筛选'})).toHaveCount(0)
 await page.locator('.region-list button[data-region="JP"]').click()
 await expect(page.locator('.node-card')).toHaveCount(1)
 await page.getByLabel('表格视图').click()
 const regions=page.getByRole('group',{name:'地区快速筛选'})
 await expect(regions).toBeVisible()
 await expect(regions.getByRole('button',{name:/JP/})).toHaveAttribute('aria-pressed','true')
 await page.getByLabel('卡片视图').click()
 await expect(regions).toHaveCount(0)
 await toggleSettings(page);await (await setting(page,'首页地图',{exact:true})).uncheck();await toggleSettings(page)
 await expect(regions).toBeVisible()
 await expect(regions.locator('img')).toHaveCount(6)
 await regions.getByRole('button',{name:'所有地区',exact:true}).click()
 await expect(page.locator('.node-card')).toHaveCount(6)
 await page.reload();await expect(regions).toBeVisible()
 await page.setViewportSize({width:320,height:900})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 await page.screenshot({path:'tests/artifacts/regions-flags-mobile.png'})
 await toggleSettings(page);await (await setting(page,'首页地图',{exact:true})).check();await toggleSettings(page)
 await expect(regions).toBeVisible()
 await expect(page.locator('.region-atlas')).toHaveCount(0)
 await page.getByRole('button',{name:'选择地区',exact:true}).click()
  await page.getByRole('dialog').getByRole('button',{name:/日本/}).click()
 await expect(page.locator('.node-card')).toHaveCount(1)
 await page.screenshot({path:'tests/artifacts/regions-mobile.png'})
 await page.setViewportSize({width:1440,height:1000})
 await expect(regions).toHaveCount(0)
 await expect(page.locator('.region-list button[data-region="JP"]')).toHaveAttribute('aria-pressed','true')
 await page.locator('.region-atlas').screenshot({path:'tests/artifacts/regions-map-desktop.png'})
})

for (const width of [320,390,720]) {
 test('mobile first visit keeps region and view controls at '+width+'px',async({page})=>{
  await page.setViewportSize({width,height:844})
  await page.goto('/')
  await expect(page.locator('.region-atlas,.map-placeholder')).toHaveCount(0)
  const regions=page.getByRole('group',{name:'地区快速筛选'})
  await expect(regions).toBeVisible()
  await page.getByRole('button',{name:'选择地区',exact:true}).click()
  await page.getByRole('dialog').getByRole('button',{name:/日本/}).click()
  await expect(page.locator('.node-card')).toHaveCount(1)
  await page.getByLabel('表格视图').click()
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByLabel('卡片视图').click()
  await page.reload()
  await expect(page.getByRole('button',{name:'选择地区',exact:true})).toContainText('日本')
  await page.getByRole('button',{name:'选择地区',exact:true}).click()
  await page.getByRole('dialog').getByRole('button',{name:/所有地区/}).click()
  await expect(page.locator('.node-card')).toHaveCount(6)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
  await page.setViewportSize({width:721,height:844})
  await expect(page.locator('.region-atlas')).toBeVisible()
  await page.setViewportSize({width,height:844})
  await expect(page.locator('.region-atlas')).toHaveCount(0)
 })
}

for(const appearance of ['light','dark']){
 test('region sheet layout, dismissal and focus in '+appearance,async({page})=>{
  await page.addInitScript(a=>localStorage.setItem('monitor-next',JSON.stringify({designVersion:1,appearance:a})),appearance)
  for(const width of [320,390,720]){
   await page.setViewportSize({width,height:844});await page.goto('/')
   const trigger=page.getByRole('button',{name:'选择地区',exact:true})
   await expect(trigger).toBeVisible()
   const toolbar=(await page.locator('.mobile-node-toolbar').boundingBox())!
   expect(toolbar.height).toBeLessThanOrEqual(54)
   await trigger.click()
   const dialog=page.getByRole('dialog',{name:'选择地区'})
   await expect(dialog).toBeVisible()
   const box=(await dialog.boundingBox())!
   expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(width)
   expect(Math.round(box.y+box.height)).toBe(844)
   await expect(dialog.getByRole('button',{name:/所有地区/})).toHaveAttribute('aria-pressed','true')
   expect(await page.evaluate(()=>document.body.style.overflow)).toBe('hidden')
   await page.screenshot({path:`tests/artifacts/region-sheet-${width}-${appearance}.png`})
   await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(trigger).toBeFocused()
   expect(await page.evaluate(()=>document.body.style.overflow)).not.toBe('hidden')
   await trigger.click();await dialog.getByRole('button',{name:/日本/}).click()
   await expect(trigger).toContainText('日本');await expect(trigger).toBeFocused()
   await trigger.click();await dialog.getByRole('button',{name:/所有地区/}).click()
   await page.screenshot({path:`tests/artifacts/toolbar-${width}-${appearance}.png`})
  }
 })
}
