import {test,expect} from '@playwright/test'
import {toggleSettings} from './settings'
test('country flags appear only without map and retain the selected region',async({page})=>{
 await page.goto('/')
 await expect(page.locator('.region-atlas')).toBeVisible()
 await expect(page.getByRole('group',{name:'地区快速筛选'})).toHaveCount(0)
 await page.locator('.region-list button[data-region="JP"]').click()
 await expect(page.locator('.node-card')).toHaveCount(1)
 await page.getByLabel('表格视图').click()
 const regions=page.getByRole('group',{name:'地区快速筛选'})
 await expect(regions).toBeVisible()
 await expect(regions.getByRole('button',{name:/JP/})).toHaveAttribute('aria-pressed','true')
 await page.getByLabel('卡片视图').click()
 await expect(regions).toHaveCount(0)
 await toggleSettings(page);await page.getByLabel('首页地图',{exact:true}).uncheck();await toggleSettings(page)
 await expect(regions).toBeVisible()
 await expect(regions.locator('img')).toHaveCount(6)
 await regions.getByRole('button',{name:'所有地区',exact:true}).click()
 await expect(page.locator('.node-card')).toHaveCount(6)
 await page.reload();await expect(regions).toBeVisible()
 await page.setViewportSize({width:320,height:900})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 await page.screenshot({path:'tests/artifacts/regions-flags-mobile.png'})
 await toggleSettings(page);await page.getByLabel('首页地图',{exact:true}).check();await toggleSettings(page)
 await expect(regions).toBeVisible()
 await expect(page.locator('.region-atlas')).toHaveCount(0)
 await regions.getByRole('button',{name:/JP/}).click()
 await expect(page.locator('.node-card')).toHaveCount(1)
 await page.screenshot({path:'tests/artifacts/regions-mobile.png'})
 await page.setViewportSize({width:1440,height:1000})
 await expect(regions).toHaveCount(0)
 await expect(page.locator('.region-list button[data-region="JP"]')).toHaveAttribute('aria-pressed','true')
 await page.locator('.region-atlas').screenshot({path:'tests/artifacts/regions-map-desktop.png'})
})

for (const width of [320,390,720]) {
 test('mobile first visit keeps region and view controls at '+width+'px',async({page})=>{
  await page.setViewportSize({width,height:844})
  await page.goto('/')
  await expect(page.locator('.region-atlas,.map-placeholder')).toHaveCount(0)
  const regions=page.getByRole('group',{name:'地区快速筛选'})
  await expect(regions).toBeVisible()
  await regions.getByRole('button',{name:/JP/}).click()
  await expect(page.locator('.node-card')).toHaveCount(1)
  await page.getByLabel('表格视图').click()
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByLabel('卡片视图').click()
  await page.reload()
  await expect(regions.getByRole('button',{name:/JP/})).toHaveAttribute('aria-pressed','true')
  await regions.getByRole('button',{name:'所有地区',exact:true}).click()
  await expect(page.locator('.node-card')).toHaveCount(6)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
  await page.setViewportSize({width:721,height:844})
  await expect(page.locator('.region-atlas')).toBeVisible()
  await page.setViewportSize({width,height:844})
  await expect(page.locator('.region-atlas')).toHaveCount(0)
 })
}
