import {test,expect} from '@playwright/test'
test.beforeEach(async({page})=>{await page.addInitScript(()=>{if(!localStorage.getItem('monitor-next'))localStorage.setItem('monitor-next',JSON.stringify({schemaVersion:3,infoDensity:'full',modules:{map:true}}))})})

test('desktop region bar filters nodes and disabled maps restore the region list',async({page})=>{
 let mapEnabled=true
 await page.route('**/theme-config.json',route=>route.fulfill({json:{modules:{map:mapEnabled}}}))
 await page.route('**/api/themes/hex/config',route=>route.fulfill({status:404}))
 await page.goto('/')
 const regionBar=page.locator('.home-region-bar')
 await expect(regionBar).toBeVisible()
 await expect(page.locator('.region-atlas,.map-placeholder')).toHaveCount(0)
 await expect(regionBar.getByRole('button',{name:'展开地图'})).toHaveAttribute('aria-expanded','false')
 await regionBar.getByRole('button',{name:/日本/}).click()
 await expect(page.locator('.node-card')).toHaveCount(1)
 await expect(regionBar.locator('.home-region-result')).toContainText('匹配 1 个节点')
 await expect(regionBar.getByRole('button',{name:'清除筛选'})).toBeVisible()
 await expect(page.locator('.active-filters .filter-match-count,.active-filters .clear-all-filters')).toHaveCount(0)
 await expect(page.locator('.node-browser')).toBeHidden()
 for(const width of [721,1440]){
  await page.setViewportSize({width,height:900})
  const label=(await regionBar.locator('.home-region-label').boundingBox())!
  const result=(await regionBar.locator('.home-region-result').boundingBox())!
  const bar=(await regionBar.boundingBox())!
  expect(Math.abs(label.y+label.height/2-result.y-result.height/2)).toBeLessThan(2)
  expect(bar.x+bar.width-result.x-result.width).toBeLessThan(15)
 }
 await page.locator('.desktop-results-toolbar').getByLabel('表格视图').click()
 await expect(page.locator('tbody tr')).toHaveCount(1)
 await page.locator('.desktop-results-toolbar').getByLabel('卡片视图').click()
 await expect(regionBar.getByRole('button',{name:/日本/})).toHaveAttribute('aria-pressed','true')
 await regionBar.getByRole('button',{name:'清除筛选'}).click()
 await expect(regionBar.getByRole('button',{name:/日本/})).toHaveAttribute('aria-pressed','false')
 await expect(page.locator('.node-browser')).toBeHidden()
 await expect(page.locator('.node-card')).toHaveCount(6)
 await regionBar.getByRole('button',{name:/日本/}).click()
 await regionBar.getByRole('button',{name:'展开地图'}).click()
 await expect(page.locator('.region-atlas')).toBeVisible()
 await expect(page.locator('.region-list button[data-region="JP"]')).toHaveAttribute('aria-pressed','true')
 await page.locator('.region-atlas .map-close').click()
 await expect(page.locator('.region-atlas')).toHaveCount(0)
 mapEnabled=false;await page.reload()
 const restored=page.getByRole('group',{name:'地区快速筛选'})
 await expect(regionBar).toHaveCount(0)
 await expect(restored).toBeVisible()
 await expect(restored.locator('img')).toHaveCount(6)
 await restored.getByRole('button',{name:'所有地区',exact:true}).click()
 await expect(page.locator('.node-card')).toHaveCount(6)
 await page.reload();await expect(restored).toBeVisible()
 await page.setViewportSize({width:320,height:900})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 await page.screenshot({path:'tests/artifacts/regions-flags-mobile.png'})
 mapEnabled=true;await page.reload()
 await expect(page.getByRole('button',{name:'选择地区',exact:true})).toBeVisible()
 await expect(page.locator('.region-atlas')).toHaveCount(0)
 await page.getByRole('button',{name:'选择地区',exact:true}).click()
  await page.getByRole('dialog').getByRole('button',{name:/日本/}).click()
 await expect(page.locator('.node-card')).toHaveCount(1)
 await page.screenshot({path:'tests/artifacts/regions-mobile.png'})
 await page.setViewportSize({width:1440,height:1000})
 await expect(regionBar).toBeVisible()
 await expect(regionBar.getByRole('button',{name:/日本/})).toHaveAttribute('aria-pressed','true')
 await regionBar.getByRole('button',{name:'展开地图'}).click()
 await expect(page.locator('.region-atlas')).toBeVisible()
 await page.locator('.region-atlas').screenshot({path:'tests/artifacts/regions-map-desktop.png'})
})

for (const width of [320,390,720]) {
 test('mobile first visit keeps region and view controls at '+width+'px',async({page})=>{
  await page.setViewportSize({width,height:844})
  await page.goto('/')
  await expect(page.locator('.region-atlas,.map-placeholder')).toHaveCount(0)
  const regions=page.getByRole('group',{name:'地区快速筛选'})
  await expect(regions).toBeVisible()
  await page.getByRole('button',{name:'选择地区',exact:true}).click()
  await page.getByRole('dialog').getByRole('button',{name:/日本/}).click()
  await expect(page.locator('.node-card')).toHaveCount(1)
  await page.getByLabel('表格视图').click()
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByLabel('卡片视图').click()
  await page.reload()
  await expect(page.getByRole('button',{name:'选择地区',exact:true})).toContainText('日本')
  await page.getByRole('button',{name:'选择地区',exact:true}).click()
  await page.getByRole('dialog').getByRole('button',{name:/所有地区/}).click()
  await expect(page.locator('.node-card')).toHaveCount(6)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
  await page.setViewportSize({width:721,height:844})
  await expect(page.locator('.home-region-bar')).toBeVisible()
  await expect(page.locator('.region-atlas,.map-placeholder')).toHaveCount(0)
  await page.setViewportSize({width,height:844})
  await expect(page.locator('.home-region-bar')).toHaveCount(0)
 })
}

for(const appearance of ['light','dark']){
 test('region sheet layout, dismissal and focus in '+appearance,async({page})=>{
  await page.addInitScript(a=>localStorage.setItem('monitor-next',JSON.stringify({designVersion:1,appearance:a})),appearance)
  for(const width of [320,390,720]){
   await page.setViewportSize({width,height:844});await page.goto('/')
   const trigger=page.getByRole('button',{name:'选择地区',exact:true})
   await expect(trigger).toBeVisible()
   const toolbar=(await page.locator('.mobile-node-toolbar').boundingBox())!
   expect(toolbar.height).toBeLessThanOrEqual(54)
   await trigger.click()
   const dialog=page.getByRole('dialog',{name:'选择地区'})
   await expect(dialog).toBeVisible()
   const box=(await dialog.boundingBox())!
   expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(width)
   expect(Math.round(box.y+box.height)).toBe(844)
   await expect(dialog.getByRole('button',{name:/所有地区/})).toHaveAttribute('aria-pressed','true')
   expect(await page.evaluate(()=>document.body.style.overflow)).toBe('hidden')
   await page.screenshot({path:`tests/artifacts/region-sheet-${width}-${appearance}.png`})
   await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(trigger).toBeFocused()
   expect(await page.evaluate(()=>document.body.style.overflow)).not.toBe('hidden')
   await trigger.click();await dialog.getByRole('button',{name:/日本/}).click()
   await expect(trigger).toContainText('日本');await expect(trigger).toBeFocused()
   await trigger.click();await dialog.getByRole('button',{name:/所有地区/}).click()
   await page.screenshot({path:`tests/artifacts/toolbar-${width}-${appearance}.png`})
  }
 })
}
