import {readFile} from 'node:fs/promises'
import {test,expect} from '@playwright/test'

test('all-settings reset can be cancelled without changing preferences',async({page})=>{
 await page.goto('/')
 await page.getByRole('button',{name:'显示与偏好'}).click()
 const drawer=page.locator('dialog.settings-drawer')
 await drawer.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'偏好'}).click()
 await drawer.getByRole('button',{name:'重置全部偏好'}).click()
 const confirmation=page.getByRole('dialog',{name:'重置全部偏好？'})
 await expect(confirmation).toContainText('表格列、语言、线路偏好和浏览筛选')
 await confirmation.getByRole('button',{name:'取消'}).click()
 await expect(confirmation).toHaveCount(0)
 await expect(drawer).toBeVisible()
})

test('theme settings backup restores durable settings and accepts legacy appearance files',async({page})=>{
 await page.goto('/')
 await page.evaluate(()=>localStorage.setItem('monitor-next-node-probes-v1','{"1":"2"}'))
 await page.reload()
 await page.getByRole('button',{name:'展开地图'}).click()
 await page.getByRole('button',{name:'显示与偏好'}).click()
 const drawer=page.locator('dialog.settings-drawer')
 await drawer.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'显示内容'}).click()
 await drawer.getByRole('group',{name:'表格显示'}).getByRole('button',{name:'手机表格',exact:true}).click()
 await drawer.getByRole('group',{name:'手机表格'}).getByRole('checkbox',{name:'内存'}).check()
 await drawer.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'偏好'}).click()
 await drawer.getByRole('group',{name:'Language / 语言'}).getByRole('button',{name:'English'}).click()
 const downloadEvent=page.waitForEvent('download')
 await drawer.getByRole('button',{name:'Export theme settings'}).click()
 const download=await downloadEvent
 const exported=JSON.parse(await readFile((await download.path())!,'utf8'))
 expect(exported).toMatchObject({format:'monitor-hex-settings',version:1,language:'en',mapHeight:'expanded',nodeProbes:{'1':'2'}})
 expect(exported.table.mobileColumns).toContain('memory')
 expect(exported).not.toHaveProperty('query')
 await drawer.getByRole('button',{name:'Reset all preferences',exact:true}).click()
 await page.getByRole('dialog',{name:'Reset all preferences?'}).getByRole('button',{name:'Reset preferences'}).click()
 await expect(drawer.getByRole('group',{name:'Language / 语言'}).getByRole('button',{name:'简体中文'})).toHaveAttribute('aria-pressed','true')
 expect(await page.evaluate(()=>localStorage.getItem('monitor-next-node-probes-v1'))).toBe('{}')
 await drawer.getByRole('button',{name:'导入主题配置'}).setInputFiles(await download.path() as string)
 await expect(drawer.getByRole('group',{name:'Language / 语言'}).getByRole('button',{name:'English'})).toHaveAttribute('aria-pressed','true')
 await drawer.getByRole('navigation',{name:'Settings sections'}).getByRole('button',{name:'Display'}).click()
 await expect(drawer.getByRole('group',{name:'Mobile table'}).getByRole('checkbox',{name:'Memory'})).toBeChecked()
 expect(await page.evaluate(()=>localStorage.getItem('monitor-next-node-probes-v1'))).toBe('{"1":"2"}')
 await drawer.getByRole('button',{name:'Close settings'}).click()
 await expect(page.getByRole('button',{name:'Collapse map'})).toBeVisible()
 await page.getByRole('button',{name:'Display & preferences'}).click()
 await drawer.getByRole('navigation',{name:'Settings sections'}).getByRole('button',{name:'Preferences'}).click()
 await drawer.getByRole('button',{name:'Import theme settings'}).setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({schemaVersion:3,palette:'forest',appearance:'dark'}))})
 await expect(drawer.getByRole('group',{name:'Language / 语言'}).getByRole('button',{name:'English'})).toHaveAttribute('aria-pressed','true')
 await drawer.getByRole('navigation',{name:'Settings sections'}).getByRole('button',{name:'Appearance'}).click()
 await expect(drawer.getByRole('button',{name:'Forest'})).toHaveAttribute('aria-pressed','true')
})
