import {toggleSettings} from './settings'
import { test, expect } from '@playwright/test'
import { nodes, metrics } from '../scripts/fixtures.mjs'

test('table, shared metrics, column visibility, sorting, navigation and reload persistence', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await expect(page.locator('.node-card')).toHaveCount(6)
  await expect(page.locator('.node-card').first().locator('.metric-ring strong').nth(1)).toHaveText('25%')
  await page.getByLabel('表格视图').click()
  await expect(page.locator('tbody tr')).toHaveCount(6)
  await expect(page.locator('tbody tr').first().locator('td').nth(3)).toHaveText('25%')
  await page.getByRole('columnheader',{name:/^CPU/}).getByRole('button').click()
  await expect(page.locator('tbody tr').first()).toContainText('Hong Kong')
  await page.locator('th[aria-sort=ascending] button').click()
  await expect(page.locator('tbody tr').first()).toContainText('Singapore')
  await expect(page.locator('tbody tr').last()).toContainText('London')
  await page.getByLabel('显示列', { exact: true }).click()
  await page.locator('.column-options').getByLabel('硬盘', { exact: true }).uncheck()
  await expect(page.getByRole('columnheader', { name: '硬盘', exact: true })).toHaveCount(0)
  await page.getByRole('group',{name:'地区快速筛选'}).getByRole('button',{name:'SG',exact:false}).click()
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.locator('.table-node-name').click()
  await expect(page).toHaveURL(/node\/5$/)
  await page.reload()
  await page.getByRole('button', { name: '返回总览' }).click()
  await expect(page.getByLabel('清除地区筛选')).toContainText('SG')
  await expect(page.getByRole('columnheader',{name:/^CPU/})).toHaveAttribute('aria-sort','descending')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByLabel('清除地区筛选').click()
  await page.getByLabel('卡片视图').click()
  await expect(page.locator('.node-card').first()).toContainText('Tokyo')
  await page.getByLabel('表格视图').click()
  await page.getByRole('columnheader',{name:/名称/}).getByRole('button').click()
  await expect(page.locator('.table-ping strong').first()).toBeVisible()
  await page.screenshot({ path:'tests/artifacts/v12-table.png', fullPage:true })
  await page.setViewportSize({ width:390, height:844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  expect(await page.locator('.table-scroll').evaluate(el => el.scrollWidth > el.clientWidth)).toBeTruthy()
  await page.screenshot({ path:'tests/artifacts/v12-mobile-table.png', fullPage:true })
  await page.setViewportSize({ width:320, height:740 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.locator('.table-node-name').first().click()
  await page.goBack()
  await expect(page.locator('tbody tr')).toHaveCount(6)
  expect(errors).toEqual([])
})

test('primary probe selection, latency ordering, timeout last and trend click/touch', async ({ page }) => {
  await page.route('**/api/nodes/*/metrics?*', route => {
    const id = Number(new URL(route.request().url()).pathname.split('/')[3])
    const ts = Math.floor(Date.now()/1000)
    return route.fulfill({ json: { ping: [
      {task_id:1,ts:ts-60,latency:id*10}, {task_id:1,ts,latency:id*10},
      {task_id:2,ts:ts-60,latency:id===6?null:100-id*10}, {task_id:2,ts,latency:id===6?null:101-id*10}
    ], probes:{'1':'线路 A','2':'线路 B'},loss:{'2':4.2} } })
  })
  await page.goto('/')
  await toggleSettings(page)
  await expect(page.getByLabel('主要探测线路').locator('option')).toHaveCount(3)
  await page.getByLabel('主要探测线路').selectOption('2')
  await toggleSettings(page)
  await expect(page.locator('.node-card').first().locator('.ping-probe')).toHaveCount(1)
  await expect(page.locator('.node-card').first().locator('.ping-probe').first()).toContainText('91 ms')
  await expect(page.getByRole('img',{name:'近期延迟采样'}).first()).toBeVisible()
  await page.getByLabel('表格视图').click()
  await page.getByRole('columnheader',{name:/所选线路延迟/}).getByRole('button').click()
  await expect(page.locator('tbody tr').first()).toContainText('Singapore')
  await expect(page.locator('tbody tr').last()).toContainText('London')
  await page.locator('th[aria-sort=ascending] button').click()
  await expect(page.locator('tbody tr').first()).toContainText('Tokyo')
  await expect(page.locator('tbody tr').last()).toContainText('London')
  await page.setViewportSize({width:390,height:844})
  await page.locator('.table-ping').first().getByRole('button',{name:'历史曲线'}).click()
  await expect(page).toHaveURL(/#latency$/)
  await expect(page.locator('.detail-chart-frame .recharts-wrapper')).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
})

test('connection distinguishes realtime, polling, failure and recovery', async ({ page }) => {
  let stream: any
  let socketCount = 0
  await page.routeWebSocket('**/api/ws', ws => { stream=ws; socketCount++ })
  await page.goto('/')
  await expect(page.locator('.node-card')).toHaveCount(6)
  stream.send(JSON.stringify({nodes:nodes()}))
  await expect(page.getByRole('status')).toContainText('实时连接')
  await page.getByLabel('表格视图').click()
  await page.getByLabel('卡片视图').click()
  expect(socketCount).toBe(1)
  stream.close()
  await expect(page.getByRole('status')).toContainText('轮询更新')
  await page.route('**/api/nodes', r=>r.fulfill({status:503,body:'Unavailable'}))
  await expect(page.getByRole('status')).toContainText('连接中断', {timeout:12000})
  await page.unroute('**/api/nodes')
  await expect(page.getByRole('status')).toContainText('轮询更新', {timeout:12000})
  stream.send(JSON.stringify({nodes:nodes()}))
  await expect(page.getByRole('status')).toContainText('实时连接')
  await expect(page.getByText(/最后更新：/)).toBeVisible()
})

test('100 nodes: stable filtering and history concurrency stays bounded', async ({ page }, testInfo) => {
  const base = nodes()[0]
  const list = Array.from({length:100},(_,i)=>({...base,id:i+1,sort:i,name:`Node ${String(i+1).padStart(3,'0')}`,country:i%2?'JP':'US'}))
  await page.route('**/api/nodes',r=>r.fulfill({json:{nodes:list}}))
  let active=0,max=0
  await page.route('**/api/nodes/*/metrics?*',async r=>{active++;max=Math.max(max,active);await new Promise(resolve=>setTimeout(resolve,30));await r.fulfill({json:metrics()});active--})
  await page.goto('/')
  await expect(page.locator('.node-card')).toHaveCount(100)
  await page.getByLabel('表格视图').click()
  const start=performance.now()
  await page.getByRole('group',{name:'地区快速筛选'}).getByRole('button',{name:'US',exact:false}).click()
  await expect(page.locator('tbody tr')).toHaveCount(50)
  const elapsed=performance.now()-start
  console.log(`100-node filter interaction including automation: ${elapsed.toFixed(1)} ms; history max concurrency is checked below`)
  await testInfo.attach('filter-timing', {body:JSON.stringify({nodes:100,elapsedMs:elapsed,note:'Includes browser automation overhead'}),contentType:'application/json'})
  expect(elapsed).toBeLessThan(1500)
  await page.getByLabel('清除地区筛选').click()
  await page.getByRole('columnheader',{name:/所选线路延迟/}).getByRole('button').click()
  await expect(page.locator('.sort-note')).toContainText('100/100', {timeout:20000})
  expect(max).toBeLessThanOrEqual(2)
  await page.screenshot({path:'tests/artifacts/v12-100-nodes.png'})
})

test('silent stream times out and malformed stream falls back without stale overwrite', async ({ page }) => {
  let stream: any
  await page.routeWebSocket('**/api/ws', ws => { stream=ws })
  await page.clock.install()
  await page.goto('/')
  await expect(page.locator('.node-card')).toHaveCount(6)
  stream.send(JSON.stringify({nodes:nodes()}))
  await expect(page.getByRole('status')).toContainText('实时连接')
  await page.clock.fastForward(16000)
  await expect(page.getByRole('status')).toContainText('轮询更新')
  await page.clock.fastForward(6000)
  stream.send('not json')
  await expect(page.getByRole('status')).toContainText('轮询更新')
  await expect(page.locator('.node-card')).toHaveCount(6)
})
