import {toggleSettings,visualSelect} from './settings'
import {test,expect,type Page} from '@playwright/test'
import {nodes,metrics} from '../scripts/fixtures.mjs'
const fixture=()=>nodes().map((n,i)=>({...n,name:`Node ${i+1}`,country:['JP','hk','SG','','XX','US'][i],os:i===5?'Windows Server':'Debian Linux'}))
async function setup(page:Page) {
 await page.route('**/api/me',r=>r.fulfill({json:{authed:false,public_page:true,site_name:'Monitor Next',github:false}}))
 await page.route('**/api/nodes',r=>r.fulfill({json:{nodes:fixture()}}))
 await page.goto('/')
 await expect(page.locator('.node-card')).toHaveCount(6)
}
test('map counts include unknown regions and small-region previews are accessible',async({page})=>{
 await setup(page)
 await expect(page.getByLabel('地图视图')).toHaveCount(0)
 await expect(page.getByRole('group',{name:'世界节点分布地图'})).toBeVisible()
 await expect(page.locator('.world-panel .section-heading')).toContainText('5 个地区')
 await expect(page.locator('.world-panel .section-heading')).toContainText('6 个节点')
 const unknown=page.locator('.region-list button').filter({hasText:'未知地区'})
 await expect(unknown).toContainText('2/2')
 const hk=page.locator('.region-list button').filter({hasText:'香港'})
 await hk.focus()
 await expect(page.locator('.map-summary')).toContainText('香港');await hk.press('Enter')
 await page.getByRole('button',{name:'查看 Node 2',exact:true}).click()
 await expect(page).toHaveURL(/node\/2$/)
 await page.getByRole('button',{name:'返回总览'}).click()
 await unknown.click()
 await expect(page.locator('.node-card')).toHaveCount(2)
 await expect(page.getByLabel('清除地区筛选')).toContainText('未知地区')
 await page.getByLabel('清除地区筛选').click()
 await expect(page.getByLabel('地图视图')).toHaveCount(0)
 await hk.click()
 await expect(page.locator('.node-card')).toHaveCount(1)
 await expect(page.locator('.node-grid')).toContainText('Node 2')
})
test('system filters persist and detail navigation works without favorites',async({page})=>{
 await setup(page)
 await page.reload()
 await expect(page.locator('.node-card')).toHaveCount(6)
 await page.getByRole('group',{name:'系统快速筛选'}).getByRole('button',{name:'Windows',exact:true}).click()
 await expect(page.locator('.node-card')).toHaveCount(1)
 await page.reload()
 await expect(page.locator('.node-card')).toHaveCount(1)
 await page.getByLabel('清除系统筛选').click()
 await page.getByRole('button',{name:'查看 Node 1',exact:true}).click()
 await page.getByRole('button',{name:'下一个节点',exact:true}).click()
 await expect(page).toHaveURL(/node\/2$/)
 await page.getByRole('button',{name:'返回总览'}).click()
 await page.getByLabel('表格视图').click()
 await expect(page.locator('tbody tr')).toHaveCount(6)
 await toggleSettings(page)
 await page.getByRole('button',{name:'重置全部偏好',exact:true}).click()
 await expect(page.locator('.node-card')).toHaveCount(6)
})

test('detail retries failed history, cancels obsolete node data and respects public closure',async({page})=>{
 let fail=true
 await page.route('**/api/nodes/*/metrics?*',r=>fail?r.fulfill({status:503,body:'test error'}):r.fulfill({json:metrics()}))
 await setup(page)
 await page.getByRole('button',{name:'查看 Node 1',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('读取历史数据失败')
 fail=false
 await page.getByRole('button',{name:'重试',exact:true}).click()
 await expect(page.getByRole('alert')).toHaveCount(0)
 await expect(page.locator('.recharts-wrapper').first()).toBeVisible()
 await page.getByRole('button',{name:'网络延迟',exact:true}).click()
 await page.getByRole('button',{name:'24 小时',exact:true}).click()
 await expect(page.getByRole('button',{name:'7 天',exact:true})).toHaveCount(0)
 await page.getByLabel('切换节点').selectOption('3')
 await expect(page).toHaveURL(/node\/3#latency$/)
 await expect(page.getByRole('button',{name:'资源',exact:true})).toBeVisible()
 await page.reload()
 await expect(page).toHaveURL(/node\/3#latency$/)
 await page.route('**/api/me',r=>r.fulfill({json:{authed:false,public_page:false,site_name:'Closed',github:false}}))
 await page.route('**/admin/',r=>r.fulfill({body:'Admin login'}))
 await page.reload({waitUntil:'commit'}).catch(error=>{if(!String(error).includes('ERR_ABORTED'))throw error})
 await expect(page).toHaveURL(/\/admin\/$/)
})
test('English overview, appearance, map and detail have translated UI and no mobile overflow',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await setup(page)
 await expect(page.getByRole('button',{name:'套餐与费用',exact:false})).toHaveCount(0)
 await page.getByLabel('Language / 语言').selectOption('en')
 await expect(page.getByRole('button',{name:'Plans & costs',exact:false})).toHaveCount(0)
 await expect(page.locator('html')).toHaveAttribute('lang','en-US')
 await expect(page.getByRole('heading',{name:'Server overview',exact:false})).toBeVisible()
 await toggleSettings(page)
 await expect(page.locator('.palette-options').getByRole('button',{name:'Forest',exact:true})).toHaveCount(1)
 for(const width of [1440,390,320]) {
  await page.setViewportSize({width,height:1000})
  for(const layout of ['comfortable','compact']) {
   await visualSelect(page,'layout',layout)
   expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width}/${layout}`).toBeTruthy()
  }
 }
 await visualSelect(page,'layout','comfortable')
 await page.locator('.preferences').screenshot({path:'tests/artifacts/v15-en-mobile-settings.png',style:'header{visibility:hidden}'})
 await toggleSettings(page)
 expect((await page.locator('main').innerText()).match(/[\u3400-\u9fff]+/g)).toBeNull()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 await page.setViewportSize({width:1440,height:1000});await expect(page.getByLabel('Map view')).toHaveCount(0)
 await page.locator('.region-list button').filter({hasText:'Hong Kong'}).focus()
 await expect(page.locator('.map-summary')).toContainText('Hong Kong')
 await page.setViewportSize({width:1440,height:1000})
 await page.locator('.world-panel').screenshot({path:'tests/artifacts/v15-map-en.png',style:'header{visibility:hidden}'})
 await page.getByLabel('Card view').click()
 await page.getByRole('button',{name:'View Node 1',exact:true}).click()
 await expect(page.getByRole('button',{name:'Resources',exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:'7 days',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Network latency',exact:true}).click()
 await expect(page.getByRole('button',{name:'24 hours',exact:true})).toBeVisible()
 await page.locator('.node-detail').screenshot({path:'tests/artifacts/v15-detail-en.png',style:'header{visibility:hidden}'})
 expect((await page.locator('main').innerText()).match(/[\u3400-\u9fff]+/g)).toBeNull()
 await page.reload()
 await expect(page.locator('html')).toHaveAttribute('lang','en-US')
 await expect(page).toHaveURL(/node\/1#latency$/)
 await page.getByLabel('Language / 语言').selectOption('zh')
 await expect(page.getByRole('button',{name:'资源',exact:true})).toBeVisible()
 expect(errors).toEqual([])
})

test('obsolete detail request is aborted when switching nodes',async({page})=>{
 let release:()=>void=()=>{}
 let requested=false
 await page.route('**/api/nodes/1/metrics?*',async r=>{
  if(new URL(r.request().url()).searchParams.get('series')==='metrics') {
   requested=true
   await new Promise<void>(resolve=>{release=resolve})
  }
  await r.fulfill({json:metrics()}).catch(()=>{})
 })
 await setup(page)
 await page.getByRole('button',{name:'查看 Node 1',exact:true}).click()
 await expect.poll(()=>requested).toBe(true)
 const failed=page.waitForEvent('requestfailed',{predicate:r=>r.url().includes('/nodes/1/metrics')&&r.url().includes('series=metrics')})
 await page.getByLabel('切换节点').selectOption('2')
 await failed
 release()
 await expect(page.locator('.node-detail h2')).toHaveText('Node 2')
 await expect(page.locator('.recharts-wrapper').first()).toBeVisible()
})
test('English remains usable when storage is disabled',async({page})=>{
 await page.addInitScript(()=>{
  Object.defineProperty(window,'localStorage',{get(){throw Error('blocked')}})
  Object.defineProperty(window,'sessionStorage',{get(){throw Error('blocked')}})
 })
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await setup(page)
 await page.getByLabel('Language / 语言').selectOption('en')
 await expect(page.getByText('Favorites only',{exact:false})).toHaveCount(0)
 await expect(page.locator('.node-card')).toHaveCount(6)
 await page.reload()
 await expect(page.locator('html')).toHaveAttribute('lang','zh-CN')
 await expect(page.locator('.node-card')).toHaveCount(6)
 expect(errors).toEqual([])
})

