import {test,expect} from '@playwright/test'
import {nodes} from '../scripts/fixtures.mjs'
test('always-visible route charts preserve timeout gaps and device information without a quota',async({page})=>{
 const now=Math.floor(Date.now()/1000)
 await page.route('**/api/nodes',r=>r.fulfill({json:{nodes:[{...nodes()[0],traffic_limit:0,cpu_name:'A very long CPU model with a full description to inspect on touch devices'}]}}))
 await page.route('**/api/nodes/*/metrics?*',r=>r.fulfill({json:{ping:[{task_id:1,ts:now-10000,latency:20},{task_id:1,ts:now-100,latency:30},{task_id:1,ts:now-50,latency:null},{task_id:1,ts:now,latency:40},{task_id:2,ts:now-9000,latency:null}],probes:{'1':'Route A','2':'Route B'},loss:{'1':25,'2':100}}}))
 await page.goto('/')
 const card=page.locator('.node-card')
 await expect(card.locator('.latency-columns')).toHaveCount(1)
 await expect(card.locator('.latency-columns').first().locator('i')).toHaveCount(4)
 await expect(card.locator('.latency-columns').first().locator('[data-tone=timeout]')).toHaveCount(1)
 await card.getByLabel('节点探测线路').selectOption('2')
 await expect(card.locator('.ping-stale')).toContainText('较旧记录')
 await expect(card.locator('.node-more')).toBeVisible()
 await expect(card.locator('.quota')).toHaveCount(0)
 await page.setViewportSize({width:320,height:844})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 await expect(card.getByRole('button',{name:'采样信息'})).toHaveCount(0)
 await card.getByRole('button',{name:'查看全部 2 条线路'}).click()
 await expect(page).toHaveURL(/node\/1#latency$/)
 await expect(page.locator('.node-detail')).toContainText('A very long CPU model')
 await expect(page.locator('.node-detail')).toContainText('交换空间')
 await expect(page.locator('.detail-probe-legend')).toContainText('Route B')
})
