import {toggleSettings} from './settings'
import {test,expect} from '@playwright/test'
import {nodes} from '../scripts/fixtures.mjs'
test('single-row home removes retired controls and ignores legacy hidden filters',async({page})=>{
 await page.addInitScript(()=>{sessionStorage.setItem('monitor-next-collection-v1',JSON.stringify({onlyFavorites:true,groupBy:'region'}));sessionStorage.setItem('monitor-next-browse-v1',JSON.stringify({sort:'cpu',direction:'desc'}))})
 await page.goto('/')
 await expect(page.locator('.node-card')).toHaveCount(6)
 await expect(page.locator('.node-card').first()).toContainText('Tokyo')
 const home=page.getByLabel('节点浏览', {exact:true})
 for(const name of ['排序字段','卡片分组','切换排序方向','恢复默认排序','主要探测线路'])await expect(home.getByLabel(name,{exact:true})).toHaveCount(0)
 await expect(home.getByText('仅看收藏',{exact:false})).toHaveCount(0)
 await expect(home.getByRole('button',{name:/刷新/})).toHaveCount(0)
 await expect(page.locator('.node-group-heading')).toHaveCount(0)
 await expect(home.getByLabel('卡片视图')).toBeVisible()
 await expect(home.getByRole('button',{name:'所有地区'})).toBeVisible()
})
test('settings route persists, imports and retains per-node override precedence',async({page})=>{
 await page.route('**/api/nodes/*/metrics?*',r=>r.fulfill({json:{ping:[{task_id:1,ts:Date.now()/1000,latency:20},{task_id:2,ts:Date.now()/1000,latency:80}],probes:{1:'Route A',2:'Route B'},loss:{}}}))
 await page.goto('/')
 const first=page.locator('.node-card').first()
 await first.getByLabel('节点探测线路').selectOption('1')
 await toggleSettings(page)
 const settings=page.getByRole('region',{name:'外观设置',exact:true})
 await settings.getByLabel('主要探测线路').selectOption('2')
 await toggleSettings(page)
 await expect(first.locator('.matrix-values')).toContainText('20 ms')
 await expect(page.locator('.node-card').nth(1).locator('.matrix-values')).toContainText('80 ms')
 await page.reload()
 await expect(first.locator('.matrix-values')).toContainText('20 ms')
 await expect(page.locator('.node-card').nth(1).locator('.matrix-values')).toContainText('80 ms')
 await toggleSettings(page)
 await expect(settings.getByLabel('主要探测线路')).toHaveValue('2')
 await settings.getByRole('button',{name:'恢复默认外观',exact:true}).click()
 await expect(settings.getByLabel('主要探测线路')).toHaveValue('2')
 await settings.getByLabel('导入外观偏好',{exact:true}).setInputFiles({name:'route.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({schemaVersion:2,probe:'1'}))})
 await expect(settings.getByLabel('主要探测线路')).toHaveValue('1')
})
test('2 by 2 resources show core-normalized load, aligned speeds and honest offline metrics',async({page})=>{
 const fixture=nodes();fixture[0].metrics.load=[2,1,1];fixture[0].cpu_cores=4
 await page.route('**/api/nodes',r=>r.fulfill({json:{nodes:fixture}}))
 await page.goto('/')
 for(const width of [1440,390,320]) {
  await page.setViewportSize({width,height:1000})
  const first=page.locator('.node-card').first(),items=first.locator('.resource')
  await expect(items).toHaveCount(4)
  const boxes=await items.evaluateAll(els=>els.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y}}))
  expect(boxes[0].y).toBe(boxes[1].y);expect(boxes[2].y).toBe(boxes[3].y);expect(boxes[2].y).toBeGreaterThan(boxes[0].y)
  await expect(items.last().locator('.bar-number')).toHaveText('2.00')
  await expect(items.last().locator('.resource-columns .filled')).toHaveCount(10)
  const speed=await first.locator('.speed-pair strong').evaluateAll(els=>els.map(e=>e.getBoundingClientRect().y))
  expect(speed[0]).toBe(speed[1])
  await expect(page.locator('.node-card').last().locator('.resource').last().locator('.bar-number')).toHaveText('—')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 }
})
test('old global route migrates once into persistent theme settings',async({page})=>{
 await page.addInitScript(()=>{if(!localStorage.getItem('seeded')){sessionStorage.setItem('monitor-next-browse-v1',JSON.stringify({probe:'2'}));localStorage.setItem('seeded','1')}})
 await page.goto('/');await toggleSettings(page)
 await expect(page.getByLabel('主要探测线路')).toHaveValue('2')
 await page.getByLabel('主要探测线路').selectOption('auto');await page.reload()
 await toggleSettings(page)
 await expect(page.getByLabel('主要探测线路')).toHaveValue('auto')
})
