import {test,expect} from '@playwright/test'
import {toggleSettings,visualSelect} from './settings'

test('phone first screen contains resource metrics; table remains compact and opens history',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/')
 const first=page.locator('.node-card').first();await expect(first).toBeVisible()
 const bottom=await first.locator('.resources').evaluate(e=>e.getBoundingClientRect().bottom)
 expect(bottom).toBeLessThan(844)
 for(const width of [320,390,768,1440]) {await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()}
 await page.getByLabel('表格视图').click();await expect(page.locator('.table-ping').first()).toContainText('ms')
 const heights=await page.locator('tbody tr').evaluateAll(rows=>rows.map(r=>r.getBoundingClientRect().height))
 expect(Math.max(...heights)).toBeLessThanOrEqual(64)
 await expect(page.locator('.table-route').last()).toContainText('历史数据')
 await expect(page.locator('.table-metric progress')).toHaveCount(15)
 await page.locator('.table-ping').first().getByRole('button',{name:'历史曲线'}).click()
 await expect(page).toHaveURL(/node\/1#latency$/);await expect(page.locator('.detail-chart-frame .recharts-wrapper')).toBeVisible()
 await expect(page.locator('.detail-smooth')).toContainText('平滑');await expect(page.locator('.probe-options')).toContainText('丢包')
})

test('return and browser back preserve scroll, focus and view; next node keeps latency tab',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/')
 const target=page.getByRole('button',{name:'查看 Singapore · 新加坡',exact:true})
 await target.scrollIntoViewIfNeeded();await expect(page.locator('.node-card').nth(4).locator('.latency-columns')).toBeVisible();const y=await page.evaluate(()=>scrollY)
 await target.click();await expect(page.locator('.node-detail')).toBeVisible()
 await page.getByRole('button',{name:'网络延迟',exact:true}).click()
 await page.getByRole('button',{name:'下一个节点',exact:true}).click();await expect(page).toHaveURL(/node\/6#latency$/)
 await page.getByRole('button',{name:'返回总览',exact:true}).click()
 await expect(target).toBeFocused();await expect.poll(()=>page.evaluate(()=>scrollY)).toBeCloseTo(y,0)
 await target.click();await expect(page.locator('.node-detail')).toBeVisible();await page.goBack()
 await expect(target).toBeFocused();await expect.poll(()=>page.evaluate(()=>scrollY)).toBeCloseTo(y,0)
})

test('embedded map filters cards and respects status',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('monitor-next',JSON.stringify({designVersion:1,modules:{map:true}})))
 await page.goto('/');await expect(page.getByLabel('地图视图')).toHaveCount(0)
 await expect(page.locator('.node-card')).toHaveCount(6)
 await page.locator('.region-list').getByRole('button',{name:'日本 1/1',exact:true}).click()
 await expect(page.locator('.node-card')).toHaveCount(1);await expect(page.locator('.node-grid')).toContainText('Tokyo')
 await page.locator('.node-grid').getByRole('button',{name:'查看 Tokyo · 东京主节点',exact:true}).click()
 await expect(page).toHaveURL(/node\/1$/);await page.getByRole('button',{name:'返回总览'}).click()
 await expect(page.locator('.node-card')).toHaveCount(1)
 await page.locator('.map-summary').getByRole('button',{name:'所有地区',exact:true}).click()
 await expect(page.locator('.node-card')).toHaveCount(6)
 await page.getByRole('button',{name:'离线',exact:true}).click();await expect(page.locator('.node-card')).toHaveCount(1)
 await expect(page.locator('.node-grid')).toContainText('London')
 await page.getByRole('button',{name:'地图说明'}).click();await expect(page.locator('.map-note')).toBeVisible()
 await page.getByLabel('表格视图').click();await expect(page.locator('.world-panel')).toHaveCount(0);await page.getByLabel('卡片视图').click();await expect(page.locator('.world-panel')).toBeVisible();await expect(page.locator('.node-card')).toHaveCount(1)
})

test('settings dialog traps focus, previews choices, closes with Escape and restores trigger',async({page})=>{
 await page.goto('/');const trigger=page.locator('header').getByRole('button',{name:'外观设置',exact:true})
 await toggleSettings(page);const drawer=page.getByRole('dialog',{name:'外观设置',exact:true});await expect(drawer).toBeVisible()
 await expect(page.getByRole('button',{name:'关闭设置'})).toBeFocused()
 await visualSelect(page,'palette','forest');await visualSelect(page,'graph','bar');await visualSelect(page,'layout','compact')
 await expect(page.locator('.next-theme')).toHaveAttribute('data-graph','bar')
 await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'线路',exact:true}).click()
 await expect(page.getByLabel('主要探测线路')).toBeInViewport()
 for(let i=0;i<20;i++){await page.keyboard.press('Tab');expect(await drawer.evaluate(e=>e.contains(document.activeElement))).toBeTruthy()}
 await page.keyboard.press('Escape');await expect(drawer).toHaveCount(0);await expect(trigger).toBeFocused()
 expect(await page.evaluate(()=>document.body.style.overflow)).not.toBe('hidden')
 await page.reload();await expect(page.locator('.next-theme')).toHaveAttribute('data-palette','forest')
 await page.setViewportSize({width:320,height:844});await toggleSettings(page)
 expect((await drawer.boundingBox())!.width).toBe(320)
 expect(await drawer.evaluate(e=>e.scrollWidth<=e.clientWidth)).toBeTruthy()
 await page.getByRole('button',{name:'关闭设置'}).click();await expect(drawer).toHaveCount(0)
})
